### ISSUE TITLE
Project Status

### ISSUE THREAD

**Issue by gaby** [bkahlert/libguestfs#18]
Hello @bkahlert what's the status of this project? There's quite a few PR's pending. 

I'm currently using the latest image, but trivy and other scanners are reporting vulnerabilities given the lack of updates.

Do you plan on doing further updates, or rather someone take over?

Thanks!

**Comment by bkahlert** [comment]
Hi @gaby I currently don't have time to maintain this project. If you would like to help, what do you neet?

**Comment by gaby** [comment]
@gaby I was mainly looking into the dependabot PR's getting merged. It seems the tests are failing now though. May be related to the update to `23.04` ?

Given that the tests are failing, the images on Docker Hub didn't get updated with the latest changes.

**Comment by bkahlert** [comment]
Just invested a couple of hours to—among others—find out that Ubuntu now has a default user "ubuntu" taking the same UID as the libguestfs user. Hope to have fixed that but a couple of tests still don't run.
I will release a 2.0.0-beta.0 later. You can check if that works.

**Comment by gaby** [comment]
@bkahlert Thank you for the updates. Looking forward to trying the latest. This image is literally one of the only ones available in docker hub that's up to date and usable.

**Comment by gaby** [comment]
Closing this, image is now up to date and working.

**Comment by gaby** [comment]
@bkahlert Any chance of getting a new release? The current image is very old and it triggers alerts about CVE's and outdated packages.
