### ISSUE TITLE
running guestfish commands as root?

### ISSUE THREAD

**Issue by hellt** [bkahlert/libguestfs#7]
Hi @bkahlert 
Thanks for this nice guesfish packaging.
I have a slight issue with the way users are treated by the embedded scripts.

Basically, I need to be able to execute a shell command as a root user, but even when I use it like that, the commands executed with `!someCmd` appears to be executed by `libguestfs` user

```
docker run -i --rm \
  -v ${DISK_DIR}:/work/${DISK_DIR} \
  -w /work/${DISK_DIR} \
  -e APP_USER="root" -e APP_GROUP="root" \
  -e PUID=0 -e PGID=0 \
  bkahlert/libguestfs \
  guestfish \
  --rw \
  --add ${DISK_NAME} \
  --mount /dev/sda1:/ \
  <<COMMANDS
!ls /usr/sbin
umount-all
exit
COMMANDS
```

The output of this `ls` command doesn't contain files owned by root.

On the other hand, if I use the interactive mode and just invoke the guestfish shell like that:

```
docker run -it --rm \
  -v ${DISK_DIR}:/work/${DISK_DIR} \
  -w /work/${DISK_DIR} \
  -e APP_USER="root" -e APP_GROUP="root" \
  -e PUID=0 -e PGID=0 \
  bkahlert/libguestfs \
  guestfish \
  --rw \
  --add ${DISK_NAME} \
  --mount /dev/sda1:/
```
I can type in the same `ls /usr/sbin` command and get access to the root owned files.

How can I enforce running shell commands in a non-interactive way as a root user?

**Comment by bkahlert** [comment]
You could try to run the container with `--entrypoint /bin/bash` and start the corresponding binary, e.g. guestfish yourself. Or use it directly as the alternative entrypoint. This would circumvent the user downgrade (with untested effects, in particular, due to the fact that using guestfish as root is discouraged).
